### ISSUE TITLE
Bug Error

### ISSUE THREAD

**Issue by Guillermo4060** [reiryuki/Dolby-Atmos-Razer-Phone2-Magisk-Module#1]
I come to report that in the most recent updates of the roms, for example the crdroid or the android 14 elixir project, the application does not open and the module does not work, and in the elixir project, when installing the module, the camera does not work since it says that it is running, but if I delete the module, everything is reset

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.
